version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.0
    steps:
      - checkout
      - run: env
      - run: git --no-pager log --pretty=oneline
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
